/**
 * GENERATED by `node scripts/project-media.mjs` — do not edit by hand.
 *
 * Order and captions come from the portfolio snapshot in `scripts/data/`;
 * dimensions are read off the files. The sizes are load-bearing: without
 * them the pinned horizontal scroll measures its travel before the media
 * loads and stops short of the last panel.
 */

export type ProjectAsset =
  | {
      kind: "image";
      src: string;
      /** Set on a GIF: Next's optimiser would flatten it to a still. */
      unoptimized?: boolean;
      width: number;
      height: number;
      caption?: string;
    }
  | {
      kind: "video";
      /** mp4 first, webm after it; the browser takes the first it can play. */
      sources: string[];
      poster: string;
      width: number;
      height: number;
      caption?: string;
    };

export type ProjectMedia = {
  cover: { src: string; width: number; height: number };
  assets: ProjectAsset[];
};

export const projectMedia: Record<string, ProjectMedia> = {
  "breathing-mass-hb01-structural-facade": {
    "cover": {
      "src": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/cover.png",
      "width": 1536,
      "height": 1024
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/01.png",
        "width": 1536,
        "height": 1024
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/breathing-mass-hb01-structural-facade/02.mp4",
          "/projects/projects-tabs/breathing-mass-hb01-structural-facade/02.webm"
        ],
        "poster": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/02-poster.jpg",
        "width": 1932,
        "height": 950,
        "caption": "THE ALVEOLAR SPINE – THE LUNG ANALOGY\n\nSTEP 01 – Defining the Primary Skeleton\nThe design begins by setting hard constraints for the core dimensions, including total height and radius. This phase focuses solely on structural integrity and the \"maximum envelope\" of the building structure.\n\nSTEP 02 – Primary Structural Framing & Modular Unit Integration\nThe building's stability is anchored by a Topology-Optimized Primary Skeleton. Using Alpaca Stress Analysis, the lattice density is strategically increased at high-load junctions and tapered in low-stress zones. The placement and density of the plugin masses are computationally grown along the lattice, with their distribution optimized by incident radiation for thermal regulation, wind pressure for airflow, and volumetric density.\n\nSTEP 03 – Fixed vs. Adaptive Facade\nThe placement and density of the plugin masses are computationally grown along the lattice, with their distribution optimized by incident radiation for thermal regulation, wind pressure for airflow, and volumetric density."
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/03.png",
        "width": 4133,
        "height": 3363
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/breathing-mass-hb01-structural-facade/04.mp4"
        ],
        "poster": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/04-poster.jpg",
        "width": 1600,
        "height": 900
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/breathing-mass-hb01-structural-facade/05.mp4"
        ],
        "poster": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/05-poster.jpg",
        "width": 1600,
        "height": 900
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/06.png",
        "width": 3887,
        "height": 2871
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/breathing-mass-hb01-structural-facade/07.mp4"
        ],
        "poster": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/07-poster.jpg",
        "width": 1600,
        "height": 900
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/breathing-mass-hb01-structural-facade/08.mp4"
        ],
        "poster": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/08-poster.jpg",
        "width": 1600,
        "height": 900
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/10.png",
        "width": 1767,
        "height": 1042
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/breathing-mass-hb01-structural-facade/11.jpg",
        "width": 1536,
        "height": 864,
        "caption": "STRUCTURAL CONCEPT\n\nThe structural approach of the project relies on the core that holds the entire project, where each volume is plugged onto the core. By that, the load is transferred from volume to core to foundation. 3 main cores form a triangle that turns vertical mass into a self-braced structural system."
      }
    ]
  },
  "collaborative-workflow-structure-facade-hb01": {
    "cover": {
      "src": "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/cover.png",
      "width": 690,
      "height": 670
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/01.jpg",
        "width": 3000,
        "height": 1577
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/02.mp4",
          "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/02.webm"
        ],
        "poster": "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/02-poster.jpg",
        "width": 1920,
        "height": 918
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/03.jpg",
        "width": 3000,
        "height": 1488
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/04.png",
        "width": 1087,
        "height": 355
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/05.jpg",
        "width": 2787,
        "height": 1443
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/collaborative-workflow-structure-facade-hb01/06.jpg",
        "width": 2800,
        "height": 1472
      }
    ]
  },
  "flat-dream": {
    "cover": {
      "src": "/projects/projects-tabs/flat-dream/cover-poster.jpg",
      "width": 480,
      "height": 480
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/1.png",
        "width": 1024,
        "height": 1024
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/2.png",
        "width": 1024,
        "height": 1024
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/3.jpg",
        "width": 7044,
        "height": 1277,
        "caption": "DATABASE"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/4.jpg",
        "width": 4739,
        "height": 3376
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/5.png",
        "width": 1536,
        "height": 567
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/6.jpg",
        "width": 5289,
        "height": 3025,
        "caption": "Workflow"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/7.jpg",
        "width": 6336,
        "height": 1420,
        "caption": "User Interface"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/8.png",
        "width": 1536,
        "height": 709
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/9.png",
        "width": 1536,
        "height": 689
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/10.png",
        "width": 768,
        "height": 344
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/11.png",
        "width": 768,
        "height": 352
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/12.png",
        "width": 768,
        "height": 341
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/flat-dream/13.mp4",
          "/projects/projects-tabs/flat-dream/13.webm"
        ],
        "poster": "/projects/projects-tabs/flat-dream/13-poster.jpg",
        "width": 480,
        "height": 480
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/flat-dream/14.png",
        "width": 1024,
        "height": 1024
      }
    ]
  },
  "la-cite-radieuse": {
    "cover": {
      "src": "/projects/projects-tabs/la-cite-radieuse/cover.png",
      "width": 1180,
      "height": 831
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/2.png",
        "width": 1917,
        "height": 955
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/3.png",
        "width": 1897,
        "height": 963
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/4.png",
        "width": 1873,
        "height": 915
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/5.png",
        "width": 1879,
        "height": 913
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/6.png",
        "width": 1903,
        "height": 852
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/7.png",
        "width": 1834,
        "height": 784
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/8.png",
        "width": 1872,
        "height": 883
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/9.png",
        "width": 1867,
        "height": 877
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/10.png",
        "width": 1858,
        "height": 856
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/11.png",
        "width": 1825,
        "height": 832
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/12.png",
        "width": 1897,
        "height": 913
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/13.png",
        "width": 1879,
        "height": 934
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/14.png",
        "width": 1861,
        "height": 895
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/15.png",
        "width": 1878,
        "height": 946
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/la-cite-radieuse/16.png",
        "width": 3983,
        "height": 4574
      }
    ]
  },
  "le-monstre-merveille": {
    "cover": {
      "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-cover.png",
      "width": 1672,
      "height": 941
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-01.jpg",
        "width": 4785,
        "height": 3040,
        "caption": "Design Concept & Computational Design System: The architectural concept is based on three main zones, organized along a central axis. The existing building envelope is preserved, while a new internal structure defines circulation, spatial separation, and visual continuity. A key design move is the central space, which acts as the heart of the project. This void allows light to penetrate deep into the space and organizes movement through ramps and bridges, creating a continuous architectural promenade rather than isolated floors."
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-02.jpg",
        "width": 4961,
        "height": 2952
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-03.jpg",
        "width": 4961,
        "height": 2950,
        "caption": "Computational Design Methodology & Form Finding Process: For the workflow, the 3 elements created follow the same form-finding using Kangaroo with slightly different setups. For the central area, the approach after using Kangaroo was to create a triangulated tiling that closes at the end and opens in the center of the space using the pull point and scale to get the final shape alongside the main structure using the multipipe. The side consists of the kangaroo and truncation approach. While the separator area follows the same architecture of the central roof, with a difference in the final tiling approach created using Perlin Noise in Python, followed by a cull pattern based on certain points to create a sort of gate to the balconies."
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-04.jpg",
        "width": 4961,
        "height": 3037,
        "caption": "Computational Design Methodology & Form Finding Process: For the workflow, the 3 elements created follow the same form-finding using Kangaroo with slightly different setups. For the central area, the approach after using Kangaroo was to create a triangulated tiling that closes at the end and opens in the center of the space using the pull point and scale to get the final shape alongside the main structure using the multipipe. The side consists of the kangaroo and truncation approach. While the separator area follows the same architecture of the central roof, with a difference in the final tiling approach created using Perlin Noise in Python, followed by a cull pattern based on certain points to create a sort of gate to the balconies."
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-05.jpg",
        "width": 4961,
        "height": 3009
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-06.jpg",
        "width": 4961,
        "height": 3006
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-07.png",
        "width": 1672,
        "height": 941
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-08.png",
        "width": 1254,
        "height": 1254
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-009.png",
        "width": 1672,
        "height": 941
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/le-monstre-merveille/le-monstre-merveille-010.png",
        "width": 1672,
        "height": 941
      }
    ]
  },
  "lightweave-pavilion": {
    "cover": {
      "src": "/projects/projects-tabs/lightweave-pavilion/cover.png",
      "width": 910,
      "height": 513
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/1.png",
        "width": 1125,
        "height": 603
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/2.png",
        "width": 1132,
        "height": 580
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/3.png",
        "width": 1138,
        "height": 486
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/4.png",
        "width": 1132,
        "height": 607
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/5.png",
        "width": 1117,
        "height": 574
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/6.png",
        "width": 1125,
        "height": 601
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/7.png",
        "width": 1144,
        "height": 601
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/8.png",
        "width": 1126,
        "height": 610
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/lightweave-pavilion/9.mp4"
        ],
        "poster": "/projects/projects-tabs/lightweave-pavilion/9-poster.jpg",
        "width": 1280,
        "height": 720
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/lightweave-pavilion/10.png",
        "width": 888,
        "height": 508
      }
    ]
  },
  "morphing-sands": {
    "cover": {
      "src": "/projects/projects-tabs/morphing-sands/cover.png",
      "width": 1116,
      "height": 616
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/1.png",
        "width": 1099,
        "height": 610
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/2.png",
        "width": 1536,
        "height": 772
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/3.png",
        "width": 1536,
        "height": 765
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/4.png",
        "width": 1414,
        "height": 552
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/5.png",
        "width": 1117,
        "height": 568
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/morphing-sands/6.mp4"
        ],
        "poster": "/projects/projects-tabs/morphing-sands/6.png",
        "width": 1280,
        "height": 720
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/7.png",
        "width": 1069,
        "height": 567
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/8.png",
        "width": 1057,
        "height": 541
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/9.png",
        "width": 1057,
        "height": 547
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/10.png",
        "width": 1051,
        "height": 498
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/11.png",
        "width": 1095,
        "height": 558
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/12.png",
        "width": 1120,
        "height": 538
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/morphing-sands/14.mp4"
        ],
        "poster": "/projects/projects-tabs/morphing-sands/14-poster.jpg",
        "width": 1600,
        "height": 900
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/morphing-sands/15.mp4"
        ],
        "poster": "/projects/projects-tabs/morphing-sands/15.png",
        "width": 1600,
        "height": 900
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/16.png",
        "width": 1068,
        "height": 514
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/morphing-sands/17.png",
        "width": 1102,
        "height": 610
      }
    ]
  },
  "nyc-urban-land-use": {
    "cover": {
      "src": "/projects/projects-tabs/nyc-urban-land-use/cover.png",
      "width": 1177,
      "height": 855
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/1.png",
        "width": 985,
        "height": 543
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/2.png",
        "width": 648,
        "height": 652
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/3.png",
        "width": 1044,
        "height": 375
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/4.png",
        "width": 903,
        "height": 556
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/5.png",
        "width": 1536,
        "height": 757
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/6.png",
        "width": 1536,
        "height": 751,
        "caption": "We shifted strategy, from predicting shop types to classifying land use across a spatial grid with expanded features."
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/7.png",
        "width": 1536,
        "height": 785
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/8.png",
        "width": 1536,
        "height": 743
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/9.png",
        "width": 1536,
        "height": 913
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/10.png",
        "width": 1536,
        "height": 746
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/11.png",
        "width": 1536,
        "height": 739
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/12.png",
        "width": 1536,
        "height": 787
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/13.png",
        "width": 1536,
        "height": 796
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/14.png",
        "width": 1536,
        "height": 759
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/15.png",
        "width": 1536,
        "height": 992
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/16.png",
        "width": 1536,
        "height": 808
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/17.png",
        "width": 1536,
        "height": 826
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/18.png",
        "width": 1536,
        "height": 765
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/19.png",
        "width": 1536,
        "height": 765
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/20.png",
        "width": 1536,
        "height": 612
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/nyc-urban-land-use/21.png",
        "width": 1536,
        "height": 850
      }
    ]
  },
  "spatial-flow-ai-driven-industrial-layout-agent": {
    "cover": {
      "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/cover.jpg",
      "width": 1254,
      "height": 1313
    },
    "assets": [
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/00.mp4"
        ],
        "poster": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/00-poster.jpg",
        "width": 1600,
        "height": 900
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/1.png",
        "width": 1984,
        "height": 1041
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/2.png",
        "width": 1978,
        "height": 1108
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/3.png",
        "width": 1024,
        "height": 555
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/4.png",
        "width": 2542,
        "height": 1315
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/5.png",
        "width": 2533,
        "height": 1270
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/6.png",
        "width": 1536,
        "height": 738
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/7.mp4",
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/7.webm"
        ],
        "poster": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/7-poster.jpg",
        "width": 1080,
        "height": 674
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/8.png",
        "width": 2503,
        "height": 583
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/9.png",
        "width": 2530,
        "height": 1192
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/10.png",
        "width": 2527,
        "height": 1270
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/11.png",
        "width": 2476,
        "height": 1258
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/12.png",
        "width": 1536,
        "height": 756
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/13.mp4",
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/13.webm"
        ],
        "poster": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/13-poster.jpg",
        "width": 1080,
        "height": 674
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/14.mp4",
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/14.webm"
        ],
        "poster": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/14-poster.jpg",
        "width": 1080,
        "height": 674
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/15.mp4",
          "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/15.webm"
        ],
        "poster": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/15-poster.jpg",
        "width": 1080,
        "height": 674
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/16.png",
        "width": 2523,
        "height": 1255
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/17.png",
        "width": 2508,
        "height": 1155
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/spatial-flow-ai-driven-industrial-layout-agent/18.jpg",
        "width": 1122,
        "height": 1402
      }
    ]
  },
  "hyper-builder-vertical-community-generator": {
    "cover": {
      "src": "/projects/projects-tabs/hyper-builder-vertical-community-generator/cover.png",
      "width": 1920,
      "height": 662
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/hyper-builder-vertical-community-generator/01.png",
        "width": 3203,
        "height": 732
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/02.mp4",
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/02.webm"
        ],
        "poster": "/projects/projects-tabs/hyper-builder-vertical-community-generator/02-poster.jpg",
        "width": 1492,
        "height": 760,
        "caption": "Viewport workflow and results in action"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/hyper-builder-vertical-community-generator/03.png",
        "width": 1920,
        "height": 662,
        "caption": "Key components of the web app"
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/04.mp4",
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/04.webm"
        ],
        "poster": "/projects/projects-tabs/hyper-builder-vertical-community-generator/04-poster.jpg",
        "width": 1156,
        "height": 810
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/05.mp4",
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/05.webm"
        ],
        "poster": "/projects/projects-tabs/hyper-builder-vertical-community-generator/05-poster.jpg",
        "width": 346,
        "height": 390
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/06.mp4",
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/06.webm"
        ],
        "poster": "/projects/projects-tabs/hyper-builder-vertical-community-generator/06-poster.jpg",
        "width": 330,
        "height": 432
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/07.mp4",
          "/projects/projects-tabs/hyper-builder-vertical-community-generator/07.webm"
        ],
        "poster": "/projects/projects-tabs/hyper-builder-vertical-community-generator/07-poster.jpg",
        "width": 394,
        "height": 190
      }
    ]
  },
  "geometry-of-intelligence-hb01": {
    "cover": {
      "src": "/projects/projects-tabs/geometry-of-intelligence-hb01/cover.png",
      "width": 2240,
      "height": 1260
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geometry-of-intelligence-hb01/01.jpg",
        "width": 2560,
        "height": 1070
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geometry-of-intelligence-hb01/02.jpg",
        "width": 1410,
        "height": 1283
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geometry-of-intelligence-hb01/03.jpg",
        "width": 2867,
        "height": 1432
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geometry-of-intelligence-hb01/04.jpg",
        "width": 2872,
        "height": 1154
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geometry-of-intelligence-hb01/05.jpg",
        "width": 2560,
        "height": 1467
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geometry-of-intelligence-hb01/06.jpg",
        "width": 2560,
        "height": 1339
      }
    ]
  },
  "automated-metadata-extraction-hb01": {
    "cover": {
      "src": "/projects/projects-tabs/automated-metadata-extraction-hb01/cover.png",
      "width": 2240,
      "height": 1260
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/automated-metadata-extraction-hb01/01.png",
        "width": 1646,
        "height": 910,
        "caption": "Cross-functional stakeholders of the project"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/automated-metadata-extraction-hb01/02.png",
        "width": 2452,
        "height": 866
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/automated-metadata-extraction-hb01/03.png",
        "width": 1733,
        "height": 1203
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/automated-metadata-extraction-hb01/06.mp4"
        ],
        "poster": "/projects/projects-tabs/automated-metadata-extraction-hb01/06-poster.jpg",
        "width": 1920,
        "height": 1080
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/automated-metadata-extraction-hb01/04.png",
        "width": 1650,
        "height": 811,
        "caption": "A series of tables generated by the automation, one per geometry imported into Speckle."
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/automated-metadata-extraction-hb01/05.png",
        "width": 1345,
        "height": 887,
        "caption": "Validation tables check for errors and for changes against the previous version: every status marks where data matches, is missing, or has been modified."
      }
    ]
  },
  "geomorphing-terrascape-chihuahua": {
    "cover": {
      "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/cover.png",
      "width": 2048,
      "height": 1150
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/01.png",
        "width": 2048,
        "height": 1250,
        "caption": "Communal public space"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/02.png",
        "width": 1918,
        "height": 567,
        "caption": "Architectural design principles and chosen typology"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/03.png",
        "width": 960,
        "height": 540
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/04.png",
        "width": 960,
        "height": 540
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/05.png",
        "width": 1757,
        "height": 873
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/geomorphing-terrascape-chihuahua/13.mp4"
        ],
        "poster": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/13-poster.jpg",
        "width": 1920,
        "height": 1080,
        "caption": "Terrain-to-grid workflow: TSP path optimisation projected onto the module grid"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/06.png",
        "width": 1918,
        "height": 1078,
        "caption": "Monoceros wave function collapse solver: rule-based architectural aggregation"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/07.png",
        "width": 695,
        "height": 1071
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/08.png",
        "width": 1205,
        "height": 927
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/09.png",
        "width": 1868,
        "height": 592,
        "caption": "Environmental resilience strategies"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/10.png",
        "width": 1918,
        "height": 1078,
        "caption": "Color-coded isometric view"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/11.png",
        "width": 1918,
        "height": 1078,
        "caption": "Ambient isometric view"
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/geomorphing-terrascape-chihuahua/14.mp4"
        ],
        "poster": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/14-poster.jpg",
        "width": 1920,
        "height": 1080
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/geomorphing-terrascape-chihuahua/15.mp4"
        ],
        "poster": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/15-poster.jpg",
        "width": 1920,
        "height": 1080
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/geomorphing-terrascape-chihuahua/12.png",
        "width": 2048,
        "height": 1150,
        "caption": "Aerial view of the aggregation"
      }
    ]
  },
  "materia-assente": {
    "cover": {
      "src": "/projects/projects-tabs/materia-assente/cover.png",
      "width": 1539,
      "height": 928
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/materia-assente/01.png",
        "width": 443,
        "height": 438
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/materia-assente/02.png",
        "width": 960,
        "height": 351
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/materia-assente/03.png",
        "width": 694,
        "height": 430
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/materia-assente/04.png",
        "width": 661,
        "height": 376
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/materia-assente/05.mp4",
          "/projects/projects-tabs/materia-assente/05.webm"
        ],
        "poster": "/projects/projects-tabs/materia-assente/05-poster.jpg",
        "width": 1920,
        "height": 1080,
        "caption": "Displacement colour map, exaggerated by a scale factor of 10, showing where the forces concentrate."
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/materia-assente/06.mp4",
          "/projects/projects-tabs/materia-assente/06.webm"
        ],
        "poster": "/projects/projects-tabs/materia-assente/06-poster.jpg",
        "width": 1920,
        "height": 1080,
        "caption": "Galapagos minimising displacement by scaling the internal voids."
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/materia-assente/07.png",
        "width": 1539,
        "height": 928
      }
    ]
  },
  "pneumatical-incrustation": {
    "cover": {
      "src": "/projects/projects-tabs/pneumatical-incrustation/cover.png",
      "width": 2356,
      "height": 1181
    },
    "assets": [
      {
        "kind": "image",
        "src": "/projects/projects-tabs/pneumatical-incrustation/01.png",
        "width": 512,
        "height": 249
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/pneumatical-incrustation/02.jpg",
        "width": 2560,
        "height": 1440,
        "caption": "Interior of the Bab El-Louk market, filled with the pneumatical incrustations that form the stores"
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/pneumatical-incrustation/03.jpg",
        "width": 2560,
        "height": 1440
      },
      {
        "kind": "video",
        "sources": [
          "/projects/projects-tabs/pneumatical-incrustation/04.mp4",
          "/projects/projects-tabs/pneumatical-incrustation/04.webm"
        ],
        "poster": "/projects/projects-tabs/pneumatical-incrustation/04-poster.jpg",
        "width": 1760,
        "height": 864,
        "caption": "The form-finding sequence: framework, inverse extrusion, membrane, inflation, trimming, panelisation."
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/pneumatical-incrustation/05.jpg",
        "width": 2560,
        "height": 1440
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/pneumatical-incrustation/06.jpg",
        "width": 3000,
        "height": 1688
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/pneumatical-incrustation/07.jpg",
        "width": 3000,
        "height": 1688
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/pneumatical-incrustation/08.jpg",
        "width": 3000,
        "height": 1688
      },
      {
        "kind": "image",
        "src": "/projects/projects-tabs/pneumatical-incrustation/09.png",
        "width": 2560,
        "height": 1440
      }
    ]
  }
};
